# monorepo/pyproject.toml
[tool.poetry]
name = "monorepo" # パッケージ名
version = "0.1.0"
# 「monorepo」パッケージをインクルードし、そのソースは「src」ディレクトリ内にあることを指定
packages = [{ include = "monorepo", from = "src" }] 

[tool.poetry.dependencies]
python = ">=3.10"
pyyaml = "^6.0.3"
