name: CI checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # CI環境で編集可能モード(-e)インストールに必要な setuptools をインストール
    - name: Install setuptools for editable install
      run: python -m pip install setuptools

    - name: Install dependencies
      # monorepo を編集可能モードでインストールし、全ての開発依存関係をインストールします
      run: pip install -r requirements-dev.txt

    - name: Run ruff checks (Linting)
      run: ruff check .

    - name: Run mypy (Static type checking)
      # mypy のインポートパス問題を確実に防ぐため、PYTHONPATHを設定してチェックします
      run: PYTHONPATH=. mypy monorepo

    - name: Run pytest (Unit/Integration tests)
      # monorepo が -e でインストールされているため、pytest はパッケージを自動認識します
      run: python -m pytest
